### ISSUE TITLE
OpenGL warning on mac

### ISSUE THREAD

**Issue by lukeplowden** [danhearn/transforming-collections#15]
Can you post the warning you get about GL texture when you run the media player on mac?

**Comment by danhearn** [comment]
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable

**Comment by lukeplowden** [comment]
> UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable

I have an idea of what it might have been, but I don't see the warning on my end so I can't check it. Can you try to run the paths branch which I just pushed some changes to at some point?

**Comment by danhearn** [comment]
tried and still getting the error, doesn't seem to be causing any issues though...
